version: 2.1
jobs:
  build:
    docker:
      - image: tomcat # the primary container, where your job's commands are run
        auth:
          username: saifshah
          password: admin123 # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: ssh -oStrictHostKeyChecking=no -v root@43.205.14.93 # run  
       
      









